### ISSUE TITLE
APP: Develop a small react application to replace the current project visualizer

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/projects#27]
Here is how the projects are shown today: https://projects.breatheco.de
And here is a demo on how we would like them to show: https://app.moqups.com/6BuBhE3GNK/view

Here you can retrieve a JSON with all the projects: https://projects.breatheco.de/json

The application must have 2 views:
1. List the projects
2. Single project details

## Listing the projects

First, there is bunch of filters that are explained on [this link](https://app.moqups.com/6BuBhE3GNK/view/page/a6ec8a579) the idea is that students and teachers are able to find a project really fast. Filters work very similar to the [AirBnB website](https://www.airbnb.com/s/Miami--FL--United-States/homes?source=mc_search_bar&query=Miami%2C%20FL%2C%20United%20States&checkin=2019-03-19&checkout=2019-03-30&adults=0&children=0&infants=0&guests=0&place_id=ChIJEcHIDqKw2YgRZU-t3XHylv8&refinement_paths%5B%5D=%2Fhomes).

Second, the details of each project are explained on this image:
![Screen Shot 2019-03-19 at 5 23 05 PM](https://user-images.githubusercontent.com/426452/54642720-afa08700-4a6b-11e9-958d-6cdf6f34bbc6.png)

## The single project view

Please don't try parsing the markdown file, use breathecode's parser for that like this:
```
http://assets.breatheco.de/apps/markdown-parser/?path=<path to readme>
```
You have to specify the path to the readme file that you can retrieve with the raw.githubusercontent.com api, for example here is the raw markdown from the postcard project: https://raw.githubusercontent.com/breatheco-de/projects/master/p/javascript/beginner/conditional-profile-card/README.md

And here the full link including our markdown parser:
http://assets.breatheco.de/apps/markdown-parser/?path=https://raw.githubusercontent.com/breatheco-de/projects/master/p/javascript/beginner/conditional-profile-card/README.md

**Comment by alesanchezr** [comment]
@ixaxtav are you up for this task?

**Comment by ixaxtav** [comment]
> @ixaxtav are you up for this task?
Yes I will be working on this.

**Comment by ixaxtav** [comment]
https://github.com/ixaxtav/breathecode-projects  i created the views you asked me for.
