### ISSUE TITLE
SEO Optimization for the projects

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/projects#38]
- [x] Implement the helmet plugin.
- [x] Add favicon
- [x] Add title to the home view: `BreatheCode Projects - Coding Projects and exercises for people learning to code or improving their coding skills`
- [x] Propose new SEO optimizations to alejandro

**Comment by Camilocoo** [comment]
Epa listo ya te acabe de mandar el PR y para la propuesta primero deberiamos hacerle el seo audit a la pagina y de ahi ya podemos ver que nos hace falta y que mas se le puede hacer

**Comment by Camilocoo** [comment]
Add Helmet to all the pages of the website

**Comment by Camilocoo** [comment]
listo re listo , pero pues no tan listo falta hacer el audit y que quede bien hecho pero ya pude instalarle a cada pagina el helmet y que saliera bien en fb

**Comment by Camilocoo** [comment]
schema
