### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by nachovz** [breatheco-de/projects#4]
Add 
nvm install 8
nvm use 8

**Comment by jferragut** [comment]
@nachovz to which file? the readme currently shows api endpoints but no instructions really lol

**Comment by alesanchezr** [comment]
@nachovz but if you have the c9-plugins you don't have to do that.

**Comment by nachovz** [comment]
@jferragut I guess on every readme
@alesanchezr We need a link back to the c9-plugins repo (just in case)

**Comment by alesanchezr** [comment]
Ok I will leave this task for a student.

## What needs to be done?

This repository holds all the project assignments of the academy, the projects are on the directory `/p/`, for example, the CSS project `instagram feed`  is located on the following path: `/p/css/beginner/instagram-feed` ([here is the link to it](https://github.com/breatheco-de/projects/tree/master/p/css/beginner/instagram-feed))

Inside each project folder you will find the README.md that contains the project instructions. That README file is shown to all students when the project is assign to them.
  
<p align="center">
<img width="400" src="https://user-images.githubusercontent.com/426452/48204595-2e581b80-e338-11e8-8e5d-4da6d5d0ac42.gif" />
</p>
  
We need someone to update all the README.md files off all the projects that use node.js and update the instructions saying that if you are a 4Geeks Student we strongly recommend having the [c9-plugin](https://github.com/breatheco-de/c9-plugin) installed. If you are not a 4Geeks Academy student that you will have to install node.js 8+ manually.

**Comment by jferragut** [comment]
@alesanchezr @nachovz we should probably also add that if you have c9 tools, you should reinstall it to the latest version so that you can get the benefit of the fix you implemented recently regarding preload. Otherwise, they will have to open a new terminal still.

**Comment by alesanchezr** [comment]
c9 tools is deprecated! c9-plugin is the new one.

**Comment by jferragut** [comment]
@alesanchezr sorry, that is what I meant lol. I installed the c9-plugin.
